# misc
notifications:
  email: false
sudo: false

# python settings
language: python
python:
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "pypy3"

# install packages
install:
  - pip install -r requirements_dev.txt
  - pip install codecov

# run test
script:
  - python -m pytest --cov

after_success:
  - codecov
